# Generated by Django 4.2.5 on 2023-09-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='skill',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='skill_icons/'),
        ),
    ]
