# Generated by Django 4.2.5 on 2023-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_remove_skill_icon_class_skill_icon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('App', 'App'), ('Card', 'Card'), ('Web', 'Web')], default='App', max_length=20)),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
