# Generated by Django 4.2.5 on 2023-10-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_portfolioitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(default='Web', max_length=10),
        ),
    ]
