# Generated by Django 4.2.5 on 2023-10-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_remove_portfolioitem_images_portfolioitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc.portfolioitem')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='images',
            field=models.ManyToManyField(related_name='portfolio_items', to='calc.portfolioimage'),
        ),
    ]
